/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class File {
  name: string
  data: Array<number>
}
export type JsFileId = FileId
export class FileId {
  constructor()
  static upload(fileName: string, fileData: Uint8Array, repo: string, token: string): Promise<unknown>
  get(token?: string | undefined | null): Promise<File>
  __debug(): void
}
