/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class File {
  name: string
  data: Buffer
}
export type JsFileId = FileId
export class FileId {
  constructor()
  static fromRaw(assetIds: Array<number>, repo: string): FileId
  static upload(fileName: string, fileData: Array<number>, repo: string, token: string): Promise<FileId>
  get(token?: string | undefined | null): Promise<File>
  __debug(): void
}
